name: 'Setup Python and Rust Environment'
description: 'Set up Python and Rust environment for PDM projects with matrix support'

inputs:
  python-version:
    description: 'Python version for setup-python'
    required: true
    default: '3.12'
  target:
    description: 'Target architecture for maturin'
    required: true
    default: 'x86_64'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Rust toolchain
      run: rustup component add clippy rustfmt
      shell: bash

    - uses: Swatinem/rust-cache@v2

    - name: Install PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: true

    - run: pdm config venv.with_pip true
      shell: bash

    - name: Install Python dependencies
      run: pdm install --no-lock --no-editable
      shell: bash

    - name: Build and install the project using Maturin
      uses: PyO3/maturin-action@v1
      with:
        target: ${{ inputs.target }}
        command: develop
        sccache: 'true'
