name: Main

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  tests-and-type-check:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [Windows]
        python-version: ["3.11"]
        include:
          - os: Windows
            image: windows-2022
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: ${{ matrix.python-version }}

      - run: poetry show click

      - name: Run tests
        run: poetry run pytest tests --cov --cov-config=pyproject.toml --cov-report=xml

      - run: poetry show click

      - name: Check typing
        run: poetry run mypy

      - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11 for Ubuntu
        uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.11' && matrix.os == 'Ubuntu' }}
