name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Run pre-commit
        run: poetry run pre-commit run -a --show-diff-on-failure

      - name: Inspect dependencies
        run: poetry run deptry .

      - name: Check Poetry lock file consistency
        run: poetry lock --check

  tests-and-type-check:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        os: [macOS, Ubuntu, Windows]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        include:
          - os: macOS
            image: macos-12
          - os: Ubuntu
            image: ubuntu-22.04
          - os: Windows
            image: windows-2022
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: poetry run pytest tests

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Check if documentation can be built
        run: poetry run mkdocs build -s
