name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  debug-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        target: [x64, aarch64]
        python: ['3.12', 'pypy3.10']
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter ${{ steps.setup-python.outputs.python-path }}
          sccache: 'true'
