name: Release

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  set-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Upload updated pyproject.toml
        uses: actions/upload-artifact@v4
        with:
          name: pyproject-toml
          path: pyproject.toml

  linux:
    runs-on: ubuntu-22.04
    needs: [set-version]
    strategy:
      matrix:
        target: [x86_64, aarch64]
        python: ['3.12', 'pypy3.10']
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter ${{ startsWith(matrix.python, 'pypy') && matrix.python || format('python{0}', matrix.python) }}
          sccache: 'true'
          manylinux: auto

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.target }}-${{ matrix.python }}
          path: dist

  macos:
    runs-on: macos-14
    needs: [set-version]
    strategy:
      matrix:
        target: [x86_64, aarch64]
        python: ['3.12', 'pypy3.10']
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Download updated pyproject.toml
        uses: actions/download-artifact@v4
        with:
          name: pyproject-toml

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter ${{ steps.setup-python.outputs.python-path }}
          sccache: 'true'

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-${{ matrix.target }}-${{ matrix.python }}
          path: dist
